### ISSUE TITLE
PNG format question

### ISSUE THREAD

**Issue by ajh123** [byteduck/duckOS#3]
I'm making a new settings app but the new 16x16.png I've made in paint.net is displaying the missing icon instead. What png settings do I need in paint.net?

The image below is the problem, it is correctly named, and in the app's icon directory
![16x16](https://user-images.githubusercontent.com/41990982/148646626-630ebcf7-d736-400c-9d0a-8d9efafa3417.png)

**Comment by byteduck** [comment]
I believe it's because the image is saved with a palette instead of as just RGB - I believe paint.net should have an option for that. It's one of my future goals to add wider support for various image formats.

**Comment by ajh123** [comment]
Thank you! Some of my work might be a bit big for a PR but it can be found here https://github.com/ajh123-development/gtmos

**Comment by ajh123** [comment]
@byteduck In another program I've got and infinite loop, in that loop how would I read keypresses?

**Comment by ajh123** [comment]
[This](https://github.com/ajh123-development/gtmos/blob/main/programs/applications/logon/main.cpp#L38) what needed to be done. The loop may look a bit different than normal, but it works alongside the rest of the program.

Can you also enable Discussions on this repo, so non issue stuff like this can go there

**Comment by byteduck** [comment]
I’ve enabled discussions, thanks for letting me know about that! For your keyboard handler, I’m not sure if that’s going to work, since the main LibUI loop already reads all the keyboard events from Pond. You could override the on_keyboard event in your widget for this purpose, but the widget will need to be in-focus for it to receive the event. Pond actually already has a mechanism to allow windows to receive global mouse and keyboard events, I just need to implement a way to do it in LibUI.
