### ISSUE TITLE
[BUG] Kernel: `PageDirectory::used_vmem()` is less than `PageDirectory::used_pmem()`

### ISSUE THREAD

**Issue by MarcoCicognani** [byteduck/duckOS#36]
## Information

Not in every case but, as written in the title, `PageDirectory::used_vmem()` returns a value that is less than `PageDirectory::used_pmem()`.

I don't reviewed your virtual memory system in deep, then I don't know if it uses demand paging or not, but theorically they, at least, should be the same value.

## Screenshot

![image](https://user-images.githubusercontent.com/20948691/202135304-ceadcc4a-a4a1-4e55-b2d7-c9c0e53d430a.png)

## Environment

- *Manjaro GNOME Linux Latest*
- *QEMU 7.1.0*

## To Reproduce

I modified:

- `~/programs/applications/monitor/ProcessListWidget.h`
```diff
diff --git a/programs/applications/monitor/ProcessListWidget.h b/programs/applications/monitor/ProcessListWidget.h
index 6a8c5f1..ee17311 100644
--- a/programs/applications/monitor/ProcessListWidget.h
+++ b/programs/applications/monitor/ProcessListWidget.h
@@ -41,6 +41,6 @@ protected:
 private:
        ProcessListWidget();
        std::vector<Sys::Process> _processes;
-       Duck::Ptr<UI::TableView> _table_view = UI::TableView::make(5);
+       Duck::Ptr<UI::TableView> _table_view = UI::TableView::make(7);
 };
```
- `~/programs/applications/monitor/ProcessListWidget.cpp`
```diff
diff --git a/programs/applications/monitor/ProcessListWidget.cpp b/programs/applications/monitor/ProcessListWidget.cpp
index 61dbe92..62dc5d7 100644
--- a/programs/applications/monitor/ProcessListWidget.cpp
+++ b/programs/applications/monitor/ProcessListWidget.cpp
@@ -67,7 +67,13 @@ Duck::Ptr<UI::Widget> ProcessListWidget::tv_create_entry(int row, int col) {
        case 3: // Memory
                return UI::Label::make(proc.physical_mem().readable(), UI::BEGINNING);
 
-       case 4: // State
+       case 4: // Virt Memory
+               return UI::Label::make(proc.virtual_mem().readable(), UI::BEGINNING);
+
+       case 5: // Shared Memory
+               return UI::Label::make(proc.shared_mem().readable(), UI::BEGINNING);
+
+       case 6: // State
                return UI::Label::make(proc.state_name(), UI::BEGINNING);
        }
 
@@ -83,8 +89,12 @@ std::string ProcessListWidget::tv_column_name(int col) {
                case 2:
                        return "Name";
                case 3:
-                       return "Memory";
+                       return "PhysMem";
                case 4:
+                       return "VirtMem";
+               case 5:
+                       return "ShmMem";
+               case 6:
                        return "State";
        }
        return "";
@@ -107,8 +117,10 @@ int ProcessListWidget::tv_column_width(int col) {
                case 2:
                        return -1;
                case 3:
-                       return 75;
                case 4:
+               case 5:
+                       return 75;
+               case 6:
                        return 60;
        }
        return 0;
```

**Comment by byteduck** [comment]
To be completely honest... The memory system is sort of a huge mess. Parts of it have been refactored over the years, but it was never really great to begin with, and now it's just a huge pile of spaghetti. Some day when I have the time, I'm gonna gut the whole thing and rewrite it from scratch, probably.

Anyway, that is 100% definitely a bug - probably the physical memory counter not being updated properly somewhere. I do know that there's some weirdness with shared memory and which process counts the physical memory it takes up - so it's probably something to do with that. But like I said, the whole system is probably going to be replaced at some point :)

**Comment by byteduck** [comment]
I’m currently working through mostly rewriting the kernel’s memory system bit by bit in the `memory-rewrite` branch. I’ve got a buddy allocation-based system for physical memory started there, instead of the current flat linked-list implementation currently in the kernel. Virtual memory stuff hasn’t been touched yet, but that will come soon :)

**Comment by MarcoCicognani** [comment]
That's great!
Since you're rewriting all the memory subsystem it could be cool if you expose a `mmap()`-like system call, which allow mapping files with demand paging.
This will be a feature used by the dynamic linker, for example, to achieve shared text segments.

Anyway keep going,
and Great work!

**Comment by byteduck** [comment]
> Since you're rewriting all the memory subsystem it could be cool if you expose a `mmap()`-like system call, which allow mapping files with demand paging.

Yep, that's the plan - I wanted to do that, and figured I should probably do the rewrite before implementing it 🙂 I'll also probably be rethinking shared memory a little bit, making it more granular and adding support for stuff like shared CoW and indirect memory grants.

**Comment by byteduck** [comment]
Update - The memory revamp is pretty much complete at this point, minus a couple of small bugs. It now has feature parity with the old system, with the added benefit that adding new features should be a lot easier. And, since objects in physical memory are effectively decoupled from where they're mapped in virtual memory, it's a lot easier to have an object mapped in multiple places. Plus, it's all managed by reference-counted smart pointers (`kstd::Arc` and `kstd::Weak`), so there's no need to worry about freeing stuff once you're done with it.

However, one thing that still needs to be figured out is how to count memory - counting used virtual and shared memory is easy, while counting used physical memory is a little less easy. For one thing, the automagic freeing of physical pages once they're no longer used makes it a little hard to count physical memory in the first place. But if that's figured out - who's responsible for the physical memory backing shared memory? Right now, it's the process that originated it, but if it dies, then it doesn't count towards any process's physical memory count. What about CoW memory, is it counted for each process using it? Or just the original process? I'll have to read up on how this is implemented elsewhere.

**Comment by MarcoCicognani** [comment]
Great Man, I followed all the updates, I really like your system, probably I will adopt a similar stragegy for my kernel.

Yeah I know, shared memory counting is a mess, infact standard operating system, from what I know, doesn't count physical shared memory, or at least they don't treat this amount as added in the total amount of physical memory used by the process.

It could be a good idea count only the virtual amount

**Comment by byteduck** [comment]
Still working on ironing out the kinks with the new memory system, but the main issue here looks to have been solved. I'll close this for now 🙂
