### ISSUE TITLE
[SUGGESTION] Use spaces instead of tabs

### ISSUE THREAD

**Issue by MarcoCicognani** [byteduck/duckOS#51]
# Suggestion

In order to better uniform the code i suggest to move to the use of spaces, instead of tabs

**Comment by byteduck** [comment]
Hmm, I think it may be a little late for this. Since all the code is already written with tabs, I don't think there's any sense in going through and reformatting it all - I'm not sure if it would really make a tangible difference anyway, since people can adjust the width of the tabs in their editor to their liking.

Additionally, in my experience, using spaces leaves the possibility open for less uniformity if people have their editor set to use a different number of spaces than the rest of the project.

**Comment by MarcoCicognani** [comment]
Okay, I normally prefer spaces since they permit to do fine grained alignment; instead, with tabs, we must mix them

**Comment by byteduck** [comment]
Yeah, that does make sense. Unfortunately, I just don't think it's practical to move the entire codebase to spaces - I think we'll just stick with tabs to save the headache from reformatting the entire codebase.
