### ISSUE TITLE
[BUG] duckOS fails to boot on Dell Inspiron Mini 10 1011 and just resets.

### ISSUE THREAD

**Issue by RGBCat1** [byteduck/duckOS#70]
When trying to boot from an SD card on the Dell Inspiron Mini 10, the system will boot into GRUB, but resets after about 30 seconds when you select duckOS. All that happens in that time is a blinking cursor.
Specifications:
RAM: 1GB Unknown
CPU: Intel Atom N270@1.60GHz
Graphics: Intel Integrated Graphics
BIOS Revision: tried on both A04 and A06

**Comment by byteduck** [comment]
This sounds like expected behavior - duckOS doesn't have USB drivers (only IDE) so it wouldn't be able to read the SD card unless the bios is doing some sort of PATA emulation (not sure how common that is).

In either case, due to the diversity of real hardware, supporting actual machines isn't a high priority - but you're always welcome to debug it on your machines and submit a PR with fixes / drivers!
